export const CONFIG = {
  models: { extract: 'claude-haiku-4-5', judge: 'claude-sonnet-5' },
  limits: {
    maxBodyChars: 20_000,
    maxClaims: 25,
    kbLimit: 5,
    judgeConcurrency: 5,
    judgeMaxOutputTokens: 1_200,
    excerptChars: 300,
    checksPerUserPerDay: 20,
  },
  kb: { folder: 'docs', mode: 'hybrid' as const },
  job: { verifyMaxAttempts: 2, syncIndexWaitMs: 120_000 },
  cron: { name: 'docs-drift', schedule: '0 6 * * *', timezone: 'America/New_York' },
  docsBase: 'https://docs.deep.space/',
  sourcePages: [
    'index',
    'get-started/introduction',
    'get-started/quickstart',
    'concepts/architecture',
    'concepts/data-model',
    'concepts/permissions',
    'concepts/realtime-sync',
    'concepts/deployment',
    'guides/authentication',
    'guides/data-storage',
    'guides/messaging',
    'guides/collaborative-editing',
    'guides/presence-and-cursors',
    'guides/file-uploads',
    'guides/ai-chat',
    'guides/payments',
    'guides/server-actions',
    'guides/scheduled-jobs',
    'guides/background-jobs',
    'bindings/knowledge',
    'guides/external-apis',
    'guides/google-oauth',
    'guides/testing',
    'guides/secrets',
    'sdk-reference/worker/ai',
  ],
} as const
